# Generated by Django 2.2.4 on 2019-08-19 14:59

from django.db import migrations
from apps.users.models import User

def create_example_superuser(apps, schema_editor):
    user = User.objects.create_superuser(
        email="superuser@example.com",
        password="superuser"
    )
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_example_superuser)
    ]
