# Generated by Django 2.2.4 on 2019-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('author_name', models.CharField(default='', max_length=255, verbose_name='Author Name')),
                ('review_text', models.TextField(default='', verbose_name='Review Text')),
                ('review_mark', models.CharField(choices=[('negative', 'Negative'), ('positive', 'Positive'), ('neutral', 'Neutral')], default='neutral', max_length=8, verbose_name='Review Mark')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
