# Generated by Django 2.2.4 on 2019-08-19 14:12

import json, random, os
from django.db import migrations
from datetime import datetime
from apps.reviews.models import REVIEW_MARK_NEGATIVE, REVIEW_MARK_POSITIVE, REVIEW_MARK_NEUTRAL

def fill_the_data(apps, schema_editor):
    Review = apps.get_model('reviews', "Review")

    module_dir = os.path.dirname(__file__)
    file_path = os.path.join(module_dir, './0002_auto_20190819_1412.json')
    with open(file_path, 'r') as f:
        data_dict = json.load(f)

    reviews = []

    for review_raw_data in data_dict:
        review = Review(
            title=review_raw_data['title'].capitalize(),
            author_name=review_raw_data['author_name'],
            review_text=review_raw_data['review_text'],
            review_mark=random.choice([REVIEW_MARK_NEGATIVE, REVIEW_MARK_POSITIVE, REVIEW_MARK_NEUTRAL]),
            pub_date=datetime.strptime(review_raw_data['pub_date'], "%Y/%m/%d").date()
        )
        reviews.append(review)

    Review.objects.bulk_create(reviews)

def delete_all_data(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    Review.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_the_data, delete_all_data)
    ]
